### PR TITLE
Allow to override bundle identifier and version information

### PR DESCRIPTION
**Pull request by fjaeger**

### CODE REVIEW

**Comment by TroubleMakerBen** [comment]
Hi Fabian,

Thx for getting in touch. Typically, we don't allow overriding the bundle identifiers in our SDK and if we allow this in one of our SDKs, we need to support this in the others, too.
I'd love to learn more about your use case and why you want to override the values. Could you please explain this a little? If you're not comfortable sharing this publicly, shoot me an email (bereimol at myemployer dot com).
I'm looking at consequences to your proposed changes in the meantime.

I hope you have a great weekend!

Benny

**Comment by fjaeger** [comment]
I fully understand the concerns regarding overwriting the bundle identifiers.

Our use case is the development of plugins/extension to existing applications. Those plugins can use HockeyApp for crash reporting (of the host app), but they would report it also with the bundle identifier of the host app. With the proposed modification, we could use the plugin's bundle identifier in crash reports.

**Comment by anlinde** [comment]
Hi,

wouldn't this imply the following:
- The host app or other plugins can't use any 3rd party crash reporting service
- The plugin gets all crashes for the host app and all plugins

**Comment by fjaeger** [comment]
@anlinde Yes, you are right. In our case, the plugin (more precisely, its HockeySDK framework) catches all crash reports. This includes those, which are not related to the plugin.

**Comment by dhei** [comment]
Hey @fjaeger,

We appreciate your PR. Unfortunately we are not able to merge this PR at this time due to the [concern](https://github.com/bitstadium/HockeySDK-Mac/pull/125#issuecomment-326676473) mentioned by @TroubleMakerBen. Thanks for your contribution.

**Comment by guperrot** [comment]
After discussing with the team we don't plan to merge this into the official SDK for the previous concerns already discussed. Thanks for your understanding and sorry for the inconvenience it may cause.

**Pull request closed without merging**
